#!/usr/bin/env bash

set -o errexit

RC_FILE_PATH="${HOME}/.dailyrc"
ENV_DIR="DAILY_DIR"
ENV_EDITOR="DAILY_EDITOR"

# Arguments
INITIALIZE="-initialize"
SET_DIR="-set-dir"
SET_EDITOR="-set-editor"

# Usable editors
editors=("vim" "nvim" "nano" "code")

# ------------------------------
# Functions related to open file
# ------------------------------

function start_edit() {
    validate_save_dir

    local file_path="${DAILY_DIR}/$(date +"%Y%m%d").md"

    make_file_if_not_exist ${file_path}

    # Open file
    # If EDITOR is not set, vim is used as the default editor
    ${DAILY_EDITOR:-vim} ${file_path}
}

function validate_save_dir() {
    if [ -z ${DAILY_DIR} ] || [ ! -d ${DAILY_DIR} ] ; then
      echo "Please set the save directory."
      exit 1
    fi
}

function make_file_if_not_exist() {
  if [ ! -e $1 ]; then
    touch $1
  fi
}

# ------------------------------
# Functions related to set save directory
# ------------------------------

function set_save_dir_if_valid() {
  if [ $# -eq 0 ]; then
    echo "Please enter the directory path."
    exit 1
  elif [ ! -d $1 ]; then
    echo "Invalid directory path. Please enter the exsiting directory path."
    exit 1
  else
    set_save_dir $1
  fi
}

function set_save_dir() {
  # Set the save directory in config file
  sed -i '' "s|^export ${ENV_DIR}=.*|export ${ENV_DIR}=$1|" "${RC_FILE_PATH}"
}

# ------------------------------
# Functions related to set editor
# ------------------------------

function set_editor_if_valid() {
  if [ $# -eq 0 ]; then
    echo "Please enter the editor."
    exit 1
  elif [[ ! ${editors[*]} =~ $1 ]]; then
    echo "Invalid editor. Please enter the valid editor."
    exit 1
  else
    set_editor $1
  fi
}

function set_editor() {
  # Set the editor in config file
  sed -i '' "s|^export ${ENV_EDITOR}=.*|export ${ENV_EDITOR}=$1|" "${RC_FILE_PATH}"
}

# ------------------------------
# Functions related to initialize
# ------------------------------

function make_config_file() {
  # Make config file in ~/.dailyrc
  if [ ! -e ${RC_FILE_PATH} ]; then
    touch "${RC_FILE_PATH}"
    echo "export ${ENV_DIR}=" >> "${RC_FILE_PATH}"
    echo "export ${ENV_EDITOR}=" >> "${RC_FILE_PATH}"
  else
    echo "Already initialized. ${RC_FILE_PATH} exists."
  fi
}

# ------------------------------

# Source config file
if [[ -e "${RC_FILE_PATH}" ]]; then
  source "${RC_FILE_PATH}"
fi

if [ $# -eq 0 ]; then
    start_edit
elif [ "$1" = ${INITIALIZE} ]; then
    make_config_file
elif [ "$1" = ${SET_DIR} ]; then
    set_save_dir_if_valid $2
elif [ "$1" = ${SET_EDITOR} ]; then
    set_editor_if_valid $2
else
    echo "Invalid argument"
    exit 1
fi

